spring:
  profiles.active: dev
---
games:
  kino:
    url: http://applications.opap.gr/DrawsRestServices/kino/last
    format: json
---
spring:
  profiles: dev
datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://0.0.0.0:3306/game
  username: root
  password: kg1249
  max-wait: 10000
  max-active: 50
  test-on-borrow: true
jpa:
  hibernate:
    ddl-auto: validate
    dialect: org.hibernate.dialect.MySQL5Dialect
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show_sql: true
    format_sql: true
flyway:
  validateOnMigrate: false
  baselineOnMigrate: true
redis:
  host: 0.0.0.0
  port: 6379
  pass: 7Fd3*#Yv*Dd4@uCAU6JCpQnZTSB%63b?
---
spring:
  profiles: dev-docker
datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://172.17.0.2:3306/game
  username: root
  password: kg1249
  max-wait: 10000
  max-active: 50
  test-on-borrow: true
jpa:
  hibernate:
    ddl-auto: validate
    dialect: org.hibernate.dialect.MySQL5Dialect
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show_sql: false
    format_sql: true
flyway:
  validateOnMigrate: true
  baselineOnMigrate: true
redis:
  host: 0.0.0.0
  port: 6379
  pass: 7Fd3*#Yv*Dd4@uCAU6JCpQnZTSB%63b?
...
    
