---
spring:
    profiles.active: dev
---
spring:
    profiles: dev
mongodb:
    url: 0.0.0.0:32768
    db: microserviceblog
---
spring:
    profiles: prod
mongodb:
    url: 0.0.0.0:32768
    db: microserviceblog